### PR TITLE
ahud-cc as own individual HUD

### PR DESCRIPTION
**Pull request by jakadak**

### CODE REVIEW

**Comment by rbjaxter** [comment]
Why would you want to remove ahud as a parent out of curiosity? Isn't this an update of ahud (and shared in name)?

**Comment by rbjaxter** [comment]
> > Why would you want to remove ahud as a parent out of curiosity? Isn't this an update of ahud (and shared in name)?
> 
> Because I would like to have ahud-cc on the front "update" page. And this couldn't be done for huds with taged parent.

Is this expected behavior/accurate @mastercoms? Seems to defeat the purpose of the parent system, since it's ultimately to encourage people linking back to huds they based theirs off of

**Comment by mastercoms** [comment]
Yeah, I'm thinking about it, will probably add a new true/false for if you want to be listed separately from your parent. The current system was put into place so that we don't have 50 slightly different m0rehud / garm3nhud edits listed.

**Comment by mastercoms** [comment]
I included the updates myself in https://github.com/mastercomfig/hud-db/commit/ff8e26025591d63770ce1052f6e291be6846e918

**Pull request closed without merging**
