### PR TITLE
static huds

### PR DESCRIPTION
**Pull request by cjrose**
Added markdown and resources to:
- voidHUD
- voidHUD Classic
- boredHUD
- staticHUD

### CODE REVIEW

**Review by mastercoms — CHANGES_REQUESTED** [review]
static seems to be typod a few times

and use more descriptive names for the resources

**Comment by cjrose** [comment]
> static seems to be typod a few times
> 
> and use more descriptive names for the resources

that is intentional

i go by staitc

**Comment by cjrose** [comment]
I've updated my image names to be more detailed, and I've changed the author names to just say static, probably easier so nobody thinks its a mistake.

**Comment by mastercoms** [comment]
It's alright if you go by staitc, but the author name was "static" in voidHUD Classic so I wasn't sure if it was a typo or not.

**Review by mastercoms — APPROVED** [review]

**Pull request merged**
