### PR TITLE
added thughud

### PR DESCRIPTION
**Pull request by RussTIB**
Wanted to submit my hud

### CODE REVIEW

**Review by mastercoms — CHANGES_REQUESTED** [review]
The ThugHud-Pic is low quality and contains inappropriate elements for display on HUD thumbnails. The thughud description contains inappropriate text. Please fix these aspects. I understand part of the style and aesthetic of the HUD's brand is to be raunchy but please tone these down for the public hud-db information.

**Comment by RussTIB** [comment]
ok will do

**Comment by RussTIB** [comment]
may i ask if it possible to say the word erotic?

**Comment by RussTIB** [comment]
ThugHud-Pic

**Comment by RussTIB** [comment]
is this fine also?

**Pull request closed without merging**
